OPENAI_SELECTED = {
    'imagenet': [
        "a bad photo of a {}.",
        "a photo of many {}.",
        "a sculpture of a {}.",
        "a photo of the hard to see {}.",
        "a low resolution photo of the {}.",
        "a rendering of a {}.",
        "graffiti of a {}.",
        "a bad photo of the {}.",
        "a cropped photo of the {}.",
        "a tattoo of a {}.",
        "the embroidered {}.",
        "a photo of a hard to see {}.",
        "a bright photo of a {}.",
        "a photo of a clean {}.",
        "a photo of a dirty {}.",
        "a dark photo of the {}.",
        "a drawing of a {}.",
        "a photo of my {}.",
        "the plastic {}.",
        "a photo of the cool {}.",
        "a close-up photo of a {}.",
        "a black and white photo of the {}.",
        "a painting of the {}.",
        "a painting of a {}.",
        "a pixelated photo of the {}.",
        "a sculpture of the {}.",
        "a bright photo of the {}.",
        "a cropped photo of a {}.",
        "a plastic {}.",
        "a photo of the dirty {}.",
        "a jpeg corrupted photo of a {}.",
        "a blurry photo of the {}.",
        "a photo of the {}.",
        "a good photo of the {}.",
        "a rendering of the {}.",
        "a {} in a video game.",
        "a photo of one {}.",
        "a doodle of a {}.",
        "a close-up photo of the {}.",
        "a photo of a {}.",
        "the origami {}.",
        "the {} in a video game.",
        "a sketch of a {}.",
        "a doodle of the {}.",
        "a origami {}.",
        "a low resolution photo of a {}.",
        "the toy {}.",
        "a rendition of the {}.",
        "a photo of the clean {}.",
        "a photo of a large {}.",
        "a rendition of a {}.",
        "a photo of a nice {}.",
        "a photo of a weird {}.",
        "a blurry photo of a {}.",
        "a cartoon {}.",
        "art of a {}.",
        "a sketch of the {}.",
        "a embroidered {}.",
        "a pixelated photo of a {}.",
        "itap of the {}.",
        "a jpeg corrupted photo of the {}.",
        "a good photo of a {}.",
        "a plushie {}.",
        "a photo of the nice {}.",
        "a photo of the small {}.",
        "a photo of the weird {}.",
        "the cartoon {}.",
        "art of the {}.",
        "a drawing of the {}.",
        "a photo of the large {}.",
        "a black and white photo of a {}.",
        "the plushie {}.",
        "a dark photo of a {}.",
        "itap of a {}.",
        "graffiti of the {}.",
        "a toy {}.",
        "itap of my {}.",
        "a photo of a cool {}.",
        "a photo of a small {}.",
        "a tattoo of the {}.",
    ],
    'caltech101': [
        'a photo of a {}.',
        'a painting of a {}.',
        'a plastic {}.',
        'a sculpture of a {}.',
        'a sketch of a {}.',
        'a tattoo of a {}.',
        'a toy {}.',
        'a rendition of a {}.',
        'a embroidered {}.',
        'a cartoon {}.',
        'a {} in a video game.',
        'a plushie {}.',
        'a origami {}.',
        'art of a {}.',
        'graffiti of a {}.',
        'a drawing of a {}.',
        'a doodle of a {}.',
        'a photo of the {}.',
        'a painting of the {}.',
        'the plastic {}.',
        'a sculpture of the {}.',
        'a sketch of the {}.',
        'a tattoo of the {}.',
        'the toy {}.',
        'a rendition of the {}.',
        'the embroidered {}.',
        'the cartoon {}.',
        'the {} in a video game.',
        'the plushie {}.',
        'the origami {}.',
        'art of the {}.',
        'graffiti of the {}.',
        'a drawing of the {}.',
        'a doodle of the {}.',
    ],
    'dtd': [
        'a photo of a {} texture.',
        'a photo of a {} pattern.',
        'a photo of a {} thing.',
        'a photo of a {} object.',
        'a photo of the {} texture.',
        'a photo of the {} pattern.',
        'a photo of the {} thing.',
        'a photo of the {} object.',
    ],
    'eurosat': [
        'a centered satellite photo of {}.',
        'a centered satellite photo of a {}.',
        'a centered satellite photo of the {}.',
    ],
    'fgvc_aircraft': [
        'a photo of a {}, a type of aircraft.',
        'a photo of the {}, a type of aircraft.',
    ],
    'oxford_flowers': [
        'a photo of a {}, a type of flower.',
    ],
    'food101': [
        'a photo of {}, a type of food.',
    ],
    'oxford_pets': [
        'a photo of a {}, a type of pet.',
    ],
    'sun397': [
        'a photo of a {}.',
        'a photo of the {}.',
    ],
    'stanford_cars': [
        'a photo of a {}.',
        'a photo of the {}.',
        'a photo of my {}.',
        'i love my {}!',
    ],
    'ucf101': [
        'a photo of a person {}.',
        'a video of a person {}.',
        'a example of a person {}.',
        'a demonstration of a person {}.',
        'a photo of the person {}.',
        'a video of the person {}.',
        'a example of the person {}.',
        'a demonstration of the person {}.',
        'a photo of a person using {}.',
        'a video of a person using {}.',
        'a example of a person using {}.',
        'a demonstration of a person using {}.',
        'a photo of the person using {}.',
        'a video of the person using {}.',
        'a example of the person using {}.',
        'a demonstration of the person using {}.',
        'a photo of a person doing {}.',
        'a video of a person doing {}.',
        'a example of a person doing {}.',
        'a demonstration of a person doing {}.',
        'a photo of the person doing {}.',
        'a video of the person doing {}.',
        'a example of the person doing {}.',
        'a demonstration of the person doing {}.',
        'a photo of a person during {}.',
        'a video of a person during {}.',
        'a example of a person during {}.',
        'a demonstration of a person during {}.',
        'a photo of the person during {}.',
        'a video of the person during {}.',
        'a example of the person during {}.',
        'a demonstration of the person during {}.',
        'a photo of a person performing {}.',
        'a video of a person performing {}.',
        'a example of a person performing {}.',
        'a demonstration of a person performing {}.',
        'a photo of the person performing {}.',
        'a video of the person performing {}.',
        'a example of the person performing {}.',
        'a demonstration of the person performing {}.',
        'a photo of a person practicing {}.',
        'a video of a person practicing {}.',
        'a example of a person practicing {}.',
        'a demonstration of a person practicing {}.',
        'a photo of the person practicing {}.',
        'a video of the person practicing {}.',
        'a example of the person practicing {}.',
        'a demonstration of the person practicing {}.',
    ],
}

COOP_SELECTED = {
    "imagenet": [
        "itap of a {}.",
        "a bad photo of the {}.",
        "a origami {}.",
        "a photo of the large {}.",
        "a {} in a video game.",
        "art of the {}.",
        "a photo of the small {}.",
    ],
    "caltech101": ['a photo of a {}.'],
    "dtd": ['{} texture.'],
    "eurosat": ['a centered satellite photo of {}.'],
    "fgvc_aircraft": ['a photo of a {}, a type of aircraft.'],
    "oxford_flowers": ['a photo of a {}, a type of flower.'],
    "food101": ['a photo of {}, a type of food.'],
    "oxford_pets": ['a photo of a {}, a type of pet.'],
    "sun397": ['a photo of a {}.'],
    "stanford_cars": ['a photo of a {}.'],
    "ucf101": ['a photo of a person doing {}.'],
}

# This is kept empty. Laioncoco templates will be loaded from the json file in auto_promt.py   
LAIONCOCO_SELECTED = {
}
    
HANDCRAFTED_SELECTED = {
    'A picture of a {} in the wild.',
'A snapshot of a {} in its natural habitat.',
'A portrait of a {} at sunset.',
'A close-up of a {} in motion.',
'An image of a {} in black and white.',
'A photo of a {} with a unique pattern.',
'A shot of a {} with vibrant colors.',
'A photo of a {} with a textured surface.',
'An action shot of a {} in flight.',
'A photo of a {} in the rain.',
'A picture of a {} in the snow.',
'A photograph of a {} in the desert.',
'A close-up of a {}\'s eyes.',
'A photo of a {} with its offspring.',
'A shot of a {} in a playful mood.',
'An image of a {} with a distinctive silhouette.',
'A portrait of a {} with a regal bearing.',
'A photo of a {} in a reflective pose.',
'A picture of a {} in an unexpected setting.',
'A snapshot of a {} with an unusual companion.',
'An image of a {} surrounded by its natural environment.',
'A photo of a {} with an interesting texture.',
'A picture of a {} in the midst of a storm.',
'A snapshot of a {} in a candid moment.',
'A portrait of a {} with a striking expression.',
'A photo of a {} with a dreamy atmosphere.',
'An image of a {} in a dramatic pose.',
'A picture of a {} with a majestic presence.',
'A snapshot of a {} with a playful expression.',
'A photo of a {} with a peaceful aura.'
}

GPT4_SELECTED = {
"A photo of a(n) {}.",
"An image depicting a(n) {}.",
"A drawing of a(n) {}.",
"A close-up view of a(n) {}.",
"A black and white image of a(n) {}.",
"A group of {}.",
"A detailed illustration of a(n) {}.",
"A colored sketch of a(n) {}.",
"A(n) {} in its natural habitat.",
"A night shot of a(n) {}.",
"An action shot of a(n) {}.",
"A(n) {} in motion.",
"A macro shot of a(n) {}.",
"A(n) {} captured during the daytime.",
"A cartoon representation of a(n) {}.",
"A vintage photo of a(n) {}.",
"A high-resolution image of a(n) {}.",
"A(n) {} in the wild.",
"A silhouette of a(n) {}.",
"A(n) {} captured under bright light.",
"A photo of a(n) {} in shadow.",
"A vibrant, colorful image of a(n) {}.",
"A(n) {} seen from a low angle.",
"A(n) {} seen from a high angle.",
"An aerial view of a(n) {}.",
"A(n) {} captured in black and white.",
"A(n) {} taken with a fish-eye lens.",
"A(n) {} seen through a zoomed-in lens.",
"A(n) {} in a dramatic lighting.",
"An artistic rendering of a(n) {}.",
"A 3D model of a(n) {}.",
"A(n) {} against a plain background.",
"A(n) {} in a crowded scene.",
"A picture that symbolizes a(n) {}.",
"A(n) {} captured at golden hour.",
"A(n) {} reflected in water.",
"A blurred image of a(n) {}.",
"A(n) {} in a serene setting.",
"A pop art style image of a(n) {}.",
"A photo of a(n) {} taken from a distance.",
"A(n) {} seen through a microscope.",
"A(n) {} captured in extreme close-up.",
"An infra-red image of a(n) {}.",
"A(n) {} captured with a thermal camera.",
"A(n) {} taken with a long exposure.",
"A(n) {} captured in the rain.",
"A(n) {} captured in the snow.",
"A(n) {} photographed at dusk.",
"A(n) {} captured during the sunrise.",
"A(n) {} against a stark contrast background.",
"A(n) {} in a panoramic view.",
"A picture showcasing the texture of a(n) {}.",
"An HDR image of a(n) {}.",
"A(n) {} shot in portrait mode.",
"A(n) {} in a landscape view.",
"A(n) {} centered in the frame.",
"A(n) {} off-center in the frame.",
"A(n) {} caught in mid-action.",
"A(n) {} photographed with a shallow depth of field.",
"A(n) {} with a blurred background.",
"An abstract interpretation of a(n) {}.",
"A digitally enhanced image of a(n) {}.",
"A(n) {} as viewed from the side.",
"A front view of a(n) {}.",
"A back view of a(n) {}.",
"A(n) {} seen from the top.",
"A perspective shot of a(n) {}.",
"A(n) {} surrounded by nature.",
"A(n) {} against a cityscape.",
"A(n) {} in a surreal context.",
"A photograph capturing the beauty of a(n) {}.",
"An image emphasizing the details of a(n) {}.",
"A(n) {} in a monochromatic theme.",
"A(n) {} depicted with contrasting colors.",
"A visually striking image of a(n) {}.",
"A candid shot of a(n) {}.",
"A(n) {} captured in a dreamy ambiance.",
"A(n) {} framed by other elements.",
"A(n) {} photographed in soft light.",
"A(n) {} with a mirror reflection.",
}

EUROSAT_SELECTED = {
    "An aerial photograph of a(n) {}.",
"A satellite image depicting a(n) {}.",
"This image shows a(n) {} from a bird's eye view.",
"A bird's eye view of a(n) {} area.",
"A landscape predominantly covered by {}.",
"Aerial imagery showcasing a(n) {}.",
"This is a satellite view of a(n) {}.",
"A high-altitude snapshot of a(n) {}.",
"An image highlighting the characteristics of a(n) {}.",
"This image depicts a land area majorly occupied by {}.",
"This is a top-down view of a(n) {}.",
"The image provides an aerial view of a(n) {}.",
"An overhead view of a(n) {}.",
"This satellite imagery showcases a(n) {}.",
"A topographic view of a(n) {}.",
"A birds-eye view photo of a(n) {}.",
"A landscape aerial view with features of a(n) {}.",
"A high-resolution satellite image of a(n) {}.",
"Aerial footage depicting a(n) {}.",
"A high-angle shot of a(n) {}.",
"A satellite snapshot showing a(n) {}.",
"A detailed view from above of a(n) {}.",
"A region primarily covered by {} as seen from above.",
"A scenic aerial shot of a(n) {}.",
"A geographical location filled with {}.",
"This landscape is characterized by {}.",
"A top-down perspective of a(n) {}.",
"An aerial panorama of a(n) {}.",
"A wide-angle satellite image of a(n) {}.",
"A landscape type is a(n) {} in this image.",
"An aerial depiction of a(n) {}.",
"An overhead shot showing a(n) {}.",
"This image provides an overhead glimpse of a(n) {}.",
"This is a topographical depiction of a(n) {}.",
"A landform type is a(n) {} in this image.",
"A high-resolution top-down image of a(n) {}.",
"An image portraying a(n) {} from above.",
"The aerial photograph emphasizes a(n) {}.",
"A geographic snapshot of a(n) {}.",
"This is an image of a(n) {} from high above.",
"This is an aerial perspective of a(n) {}.",
"An image from above showcasing a(n) {}.",
"An image capturing a(n) {} from the sky.",
"This image exhibits a prominent {} landscape.",
"A terrain type is a(n) {} in this image.",
"A bird's eye view of a typical {}.",
"This satellite photograph is of a(n) {}.",
"An expansive view of a(n) {} from the sky.",
"The image offers a detailed look at a(n) {}.",
"This overhead shot provides a view of a(n) {}.",
"A satellite image demonstrating a(n) {}.",
"A detailed aerial survey of a(n) {}.",
"A satellite view providing details of a(n) {}.",
"This aerial imagery showcases the typical features of a(n) {}.",
"A landscape snapshot primarily showing a(n) {}.",
"An image exhibiting a(n) {} from a high vantage point.",
"A clear aerial photograph of a(n) {}.",
"This image represents a(n) {} as seen from space.",
"A high-altitude image capturing a(n) {}.",
"An image displaying a(n) {} as viewed from the sky.",
"A clear, high-resolution image of a(n) {}.",
"A picture taken from above showing a(n) {}.",
"A photograph from a satellite illustrating a(n) {}.",
"A satellite image capturing the distinctive features of a(n) {}.",
"This picture presents a(n) {} from a top-down perspective.",
"An aerial view focusing on a(n) {}.",
"This image represents a(n) {} from a high-altitude viewpoint.",
"A picture demonstrating the typical characteristics of a(n) {}.",
"This satellite image provides a clear view of a(n) {}.",
"An overhead image depicting a(n) {}.",
"A high-angle view of a(n) {}.",
"An image displaying a(n) {} as seen from a high vantage point.",
"A detailed snapshot from above of a(n) {}.",
"This image provides a satellite's perspective of a(n) {}.",
"A snapshot from space showing a(n) {}.",
"A clear view from above revealing a(n) {}.",
"An image demonstrating the landscape features of a(n) {}.",
"An overhead perspective showcasing a(n) {}.",
"A satellite picture presenting a(n) {}.",
"A bird's eye perspective depicting a(n) {}.",
}

UCF101_SELECTED = {
    "A still image from a video of {}.",
"An image depicting the action of {}.",
"A scene from a {} video.",
"A picture taken during {}.",
"A frame from a {} clip.",
"An image showing the process of {}.",
"A snapshot of {} in action.",
"A visual representation of {}.",
"A screenshot from a {} video.",
"An image that symbolizes {}.",
"An iconic image of {}.",
"An image reflecting {} activity.",
"A frame from a video demonstrating {}.",
"A photograph of someone {}.",
"A still from a video of a {}.",
"An image portraying the {} activity.",
"A capture from a video of {}.",
"An image illustrating the concept of {}.",
"A photo demonstrating {}.",
"A scene showcasing {}.",
"An image taken from a {} scene.",
"A representative picture of {}.",
"A still from a {} action.",
"An image extracted from a {} video.",
"A visual frame showing {}.",
"An image depicting the essence of {}.",
"A frame from a video showcasing {}.",
"A snapshot of an individual performing {}.",
"A photo showing the act of {}.",
"A freeze frame of a {} video.",
"An image depicting a scene from a {} video.",
"A picture that could be described as {}.",
"A screenshot of a video involving {}.",
"A photo that exemplifies {}.",
"An image that conveys {}.",
"A frame that would be seen in a {} video.",
"A representative image of a video showing {}.",
"A still shot from a {} sequence.",
"An image that is typical of {}.",
"A picture of someone engaged in {}.",
"An image taken from a {} video.",
"A photo representative of {}.",
"A frame that symbolizes {}.",
"An image from a video with the theme of {}.",
"A still from a video where someone is {}.",
"A screenshot that represents {}.",
"A representative snapshot of {}.",
"A picture illustrating {}.",
"A scene from a video depicting {}.",
"A picture showing the process of {}.",
"An image typical of a {} video.",
"A frame from a video where the main activity is {}.",
"A photo captured during {}.",
"An image from a {} performance.",
"A snapshot from a {} video.",
"An image that is symbolic of {}.",
"A photo from a {} sequence.",
"A picture from a video illustrating {}.",
"A scene in which {} is happening.",
"A still from a video capturing the act of {}.",
"A picture that could be categorized as {}.",
"An image that portrays {}.",
"A frame depicting a {} scene.",
"A photo showing {} in progress.",
"A still shot captured during {}.",
"An image taken from a {} sequence.",
"A picture showing a {} scenario.",
"A frame from a {} video.",
"An image showing a typical {} scene.",
"A photo depicting a {} action.",
"An image from a video showing someone {}.",
"A frame capturing {} in action.",
"A still image from a {} performance.",
"An image representing the theme of {}.",
"A picture depicting an example of {}.",
"An image that could be a scene from a {} video.",
"A photo taken during a {} scene.",
"A frame illustrating {}.",
"A still image showing {} in progress.",
"An image that embodies {}.",
}

IMAGENET_SELECTED = {
    "A photo of a {}.",
"This is an image of {}.",
"A close-up of a {}.",
"A drawing of a {}.",
"A {} in its natural habitat.",
"This is a cartoon of a {}.",
"This image represents a {}.",
"An illustration of a {}.",
"An artistic rendering of a {}.",
"A black and white photo of a {}.",
"An emoji of a {}.",
"A detailed picture of a {}.",
"A {} taken at night.",
"A high definition image of a {}.",
"A {} in the wild.",
"A pop art style image of a {}.",
"A graphical representation of a {}.",
"A photo from a top view of a {}.",
"A {} taken during the day.",
"A painting of a {}.",
"This image depicts a {} in motion.",
"A simple sketch of a {}.",
"An abstract interpretation of a {}.",
"A macro shot of a {}.",
"A children's drawing of a {}.",
"A {} in a cityscape.",
"A vintage photograph of a {}.",
"A {} captured during the golden hour.",
"A {} in black and white.",
"A silhouette of a {}.",
"A detailed illustration of a {}.",
"A {} during the sunrise.",
"A {} during the sunset.",
"A digital art of a {}.",
"A minimalist representation of a {}.",
"A 3D model of a {}.",
"An origami of a {}.",
"A portrait of a {}.",
"A close-up shot of a {}.",
"A detailed sketch of a {}.",
"A {} in low light.",
"A {} under a microscope.",
"A sculpture of a {}.",
"A photograph of a {} in water.",
"A {} captured with a fisheye lens.",
"A neon sign of a {}.",
"A mosaic of a {}.",
"A graphical icon of a {}.",
"A pixel art of a {}.",
"A {} from a bird's eye view.",
"A comic-style image of a {}.",
"A {} taken from a drone's perspective.",
"A chalk drawing of a {}.",
"A stained glass depiction of a {}.",
"A {} taken in the autumn season.",
"A stencil art of a {}.",
"A pop-up book image of a {}.",
"A graffiti of a {}.",
"A {} during a snowy day.",
"An ASCII art of a {}.",
"A {} in a desert environment.",
"A silhouette of a {} against the sunset.",
"An embroidered image of a {}.",
"A {} in a tropical rainforest.",
"A wireframe model of a {}.",
"A photograph of a {} in motion blur.",
"A {} in the style of impressionist painting.",
"A cross-stitch pattern of a {}.",
"A {} captured in a storm.",
"A {} made out of Lego.",
"A {} in a mountainous region.",
"A stencil graffiti of a {}.",
"A {} in infrared photography.",
"A {} depicted in a medieval tapestry.",
"A {} in a Japanese ukiyo-e style art.",
"A {} in the style of cubist painting.",
"A photograph of a {} in a safari.",
"A {} in the style of a Byzantine mosaic.",
"A {} depicted in a cave painting.",
"A watercolor painting of a {}.",
}

CALTECH101_SELECTED = {
    "An image of a(n) {}.",
"This is a photo of a(n) {}.",
"A picture that shows a(n) {}.",
"An illustration featuring a(n) {}.",
"A detailed image of a(n) {}.",
"This is definitely a(n) {}.",
"A professional photograph of a(n) {}.",
"A drawing of a(n) {}.",
"A colorful depiction of a(n) {}.",
"A clear photo demonstrating a(n) {}.",
"This image showcases a(n) {}.",
"A black and white photo of a(n) {}.",
"A snapshot of a(n) {}.",
"A stock image of a(n) {}.",
"An image that captures a(n) {}.",
"A high-resolution picture of a(n) {}.",
"A naturalistic image of a(n) {}.",
"An example of a(n) {}.",
"A typical {} shown in a photograph.",
"A textbook picture of a(n) {}.",
"An artistic rendering of a(n) {}.",
"A close-up of a(n) {}.",
"A(n) {} in its natural habitat.",
"A perfectly captured {} in this image.",
"An image that epitomizes a(n) {}.",
"A classic representation of a(n) {}.",
"An iconic image of a(n) {}.",
"A photo that distinctly shows a(n) {}.",
"A visually stunning image of a(n) {}.",
"A(n) {} as seen in a magazine.",
"An abstract portrayal of a(n) {}.",
"A symbolic representation of a(n) {}.",
"An aesthetically pleasing image of a(n) {}.",
"A(n) {} in all its glory.",
"A vintage photo of a(n) {}.",
"A digitally rendered image of a(n) {}.",
"An intricately detailed {}.",
"A stylized interpretation of a(n) {}.",
"A(n) {} in a real-world setting.",
"A(n) {} as one might see in a film.",
"A photograph taken from a textbook about {}.",
"A definitive depiction of a(n) {}.",
"A dynamic image of a(n) {}.",
"A professionally taken image of a(n) {}.",
"A vivid representation of a(n) {}.",
"A(n) {} captured at the right moment.",
"A captivating image of a(n) {}.",
"A spectacular shot of a(n) {}.",
"A comprehensive illustration of a(n) {}.",
"A stunning visual of a(n) {}.",
"An impressive snapshot of a(n) {}.",
"A photographic masterpiece of a(n) {}.",
"A(n) {} from a unique perspective.",
"A sophisticated representation of a(n) {}.",
"A charming image of a(n) {}.",
"A brilliant capture of a(n) {}.",
"A true-to-life picture of a(n) {}.",
"A graphic representation of a(n) {}.",
"A(n) {} as you would see in a documentary.",
"An elegant image of a(n) {}.",
"A beautiful portrayal of a(n) {}.",
"A breathtaking view of a(n) {}.",
"An authentic image of a(n) {}.",
"A captivating depiction of a(n) {}.",
"A photorealistic representation of a(n) {}.",
"An iconic example of a(n) {}.",
"An elaborate image of a(n) {}.",
"A(n) {} as seen through the lens of a camera.",
"An aesthetically captured image of a(n) {}.",
"A poster-like image of a(n) {}.",
"A cool picture of a(n) {}.",
"A cartoonish representation of a(n) {}.",
"An exciting image of a(n) {}.",
"A silhouette of a(n) {}.",
"A(n) {} caught in action.",
"An inspiring picture of a(n) {}.",
"A visually striking {} in the photo.",
"A dramatic representation of a(n) {}.",
"A nostalgic image of a(n) {}.",
"A powerful portrayal of a(n) {}."
}

FGVC_AIRCRAFT_SELECTED = {"A photo of a {}.",
"An illustration of a {}.",
"This is a {}.",
"A clear image of a {}.",
"A {}, as seen from the front.",
"A {}, as seen from the side.",
"A {}, as seen from the top.",
"A detailed drawing of a {}.",
"The silhouette of a {}.",
"A {}, flying in the sky.",
"A {}, on the ground.",
"An image showing the details of a {}.",
"A close-up shot of a {}.",
"The cockpit of a {}.",
"The wings of a {}.",
"The engine of a {}.",
"The tail section of a {}.",
"A {}, in mid-flight.",
"A black and white photo of a {}.",
"A colorful illustration of a {}.",
"The interior of a {}.",
"A scale model of a {}.",
"A {}, at an air show.",
"A {}, during take-off.",
"A {}, during landing.",
"A {}, in a hangar.",
"The undercarriage of a {}.",
"The landing gear of a {}.",
"A {}, in bright daylight.",
"A {}, in the evening.",
"A military {}.",
"A civilian {}.",
"A commercial {}.",
"The blueprint of a {}.",
"An iconic {}.",
"The profile view of a {}.",
"The 3D model of a {}.",
"The schematics of a {}.",
"A vintage {}.",
"A modern {}.",
"A {}, seen from below.",
"A toy replica of a {}.",
"The nose section of a {}.",
"A {}, during construction.",
"A {}, in an aircraft museum.",
"The cockpit view from a {}.",
"A {}, with extended flaps.",
"A {}, with retracted landing gear.",
"The tail number of a {}.",
"A {}, in an airline livery.",
"The pilot seat in a {}.",
"A {}, with its engines running.",
"A {}, at cruising altitude.",
"A {}, taxiing on the runway.",
"The propeller of a {}.",
"The instrument panel in a {}.",
"The jet engine of a {}.",
"A {}, undergoing maintenance.",
"The cargo bay of a {}.",
"The passenger cabin of a {}.",
"A {}, flying over the ocean.",
"A {}, flying over mountains.",
"A {}, in the middle of a maneuver.",
"The control surfaces of a {}.",
"A {}, in a unique color scheme.",
"A {}, with a special marking.",
"The fuselage of a {}.",
"A {}, in a static display.",
"The aerial view of a {}.",
"The decals on a {}.",
"A {}, in a formation flight.",
"A {}, caught in the rain.",
"The emergency exits on a {}.",
"A {}, with open hatches.",
"A {}, with a distinct livery.",
"A {}, in an historical event.",
"The seats inside a {}.",
"A {}, with its lights on.",
"A {}, producing contrails.",
"The galley of a {}."}
DTD_SELECTED = {"A photo of a {} texture",
"This image shows a {} pattern",
"The texture in this picture is {}",
"This picture illustrates a {} surface",
"An example of a {} texture",
"An image featuring a {} pattern",
"This texture resembles a {}",
"This is a type of {} texture",
"The surface appears to be {}",
"A close-up shot of a {} texture",
"The image displays a {} surface",
"This is an image of a {} texture",
"This photo represents a {} texture",
"A photograph showcasing a {} surface",
"This is a depiction of a {} texture",
"An image characterized by a {} pattern",
"A detailed image of a {} texture",
"The texture in this photo can be described as {}",
"A graphic representation of a {} texture",
"This visual image demonstrates a {} surface",
"An artistic rendition of a {} texture",
"A digital image showcasing a {} pattern",
"The texture in this snapshot is {}",
"This image gives a representation of a {} texture",
"This still showcases a {} surface",
"A visual depiction of a {} texture",
"An illustration demonstrating a {} pattern",
"The texture in this rendering can be described as {}",
"This frame displays a {} texture",
"This is a representation of a {} pattern",
"The image provides a detail of a {} surface",
"A high-resolution image of a {} texture",
"This digital representation exhibits a {} pattern",
"The texture in this picture can be characterized as {}",
"This scene demonstrates a {} texture",
"A three-dimensional representation of a {} surface",
"A photograph exemplifying a {} pattern",
"The texture in this exhibit is {}",
"This display illustrates a {} texture",
"An image that is identifiable as a {} pattern",
"The texture in this digital render is {}",
"This screenshot illustrates a {} texture",
"A picture signifying a {} pattern",
"The texture in this shot is distinctly {}",
"This render encapsulates a {} texture",
"An image interpreting a {} pattern",
"The texture in this image could be categorized as {}",
"This photograph provides a clear example of a {} texture",
"A drawing that represents a {} pattern",
"The texture in this photo is reminiscent of a {}",
"This picture brings out the {} texture",
"A computer-generated image of a {} pattern",
"The texture in this visual is particularly {}",
"This representation gives a sense of a {} texture",
"A print showcasing a {} pattern",
"The texture in this image emanates a {} feel",
"This picture conveys a {} texture",
"An image designed to show a {} pattern",
"The texture in this shot has a strong {} vibe",
"This frame brings to light a {} texture",
"A snapshot illustrating a {} pattern",
"The texture in this graphic resembles a {}",
"This image accentuates the {} texture",
"A photograph designed to highlight a {} pattern",
"The texture in this picture has a distinct {} character",
"This visualization provides an example of a {} texture",
"An image that spotlights a {} pattern",
"The texture in this image exudes a {} quality",
"This digital art showcases a {} texture",
"A visual that emphasizes a {} pattern",
"The texture in this illustration can be identified as {}",
"This display paints a picture of a {} texture",
"A photograph that underscores a {} pattern",
"The texture in this scene has a unique {} aspect",
"This picture provides a perspective on a {} texture",
"An image that stresses the {} pattern",
"The texture in this representation has a {} essence",
"This scene portrays a {} texture",
"A still that highlights a {} pattern",
"The texture in this depiction is fundamentally {}",}

OXFORD_FLOWERS_SELECTED = { 
"An image of a {} flower.",
"A close up of a {} plant.",
"A photo primarily featuring {}.",
"{} blossoms in nature.",
"The distinguishing features of {}.",
"A picture that focuses on {}.",
"A garden that is home to {}.",
"A bouquet made up of {}.",
"A botanical illustration of {}.",
"The flower called {}.",
"An image showcasing the {} species.",
"A detailed view of a {} flower.",
"A beautiful example of {}.",
"{} growing in a field.",
"A single {} bloom in focus.",
"The vibrant petals of {}.",
"The unique characteristics of {}.",
"A floral arrangement featuring {}.",
"A hand drawing of a {} flower.",
"A watercolor painting of {}.",
"The bright colors of {}.",
"A field filled with {} flowers.",
"A close up shot of {}.",
"An artistic representation of {}.",
"A botanical study of {}.",
"{} in full bloom.",
"A photograph highlighting {}.",
"A botanical garden containing {}.",
"A detailed botanical print of {}.",
"The intricate patterns of {}.",
"A macro shot of a {} flower.",
"An elegant {} in a garden.",
"A close up view of {}.",
"A lush {} plant with flowers.",
"A vibrant field of {}.",
"A digital art representation of {}.",
"A botanical sketch of {}.",
"A blooming {} in springtime.",
"The delicate petals of {}.",
"A high resolution image of {}.",
"The natural beauty of {}.",
"A picture taken in a {} flower field.",
"A pencil sketch of {}.",
"A pastel drawing of {}.",
"A photograph taken in a {} garden.",
"A {} flower captured during golden hour.",
"The fine details of {}.",
"A bouquet with {} as the star.",
"A high contrast image of {}.",
"A detailed study of {}.",
"A fresh {} bloom.",
"A stunning close-up of {}.",
"A botanical drawing of {}.",
"A painting depicting {}.",
"A field primarily filled with {}.",
"A bunch of {} flowers.",
"The beautiful {} species in bloom.",
"A botanical garden filled with {}.",
"A vivid close-up of {}.",
"An oil painting of {}.",
"A photograph focusing on {}.",
"The elegant blooms of {}.",
"A detailed macro shot of {}.",
"A garden filled with {}.",
"The beauty of {} in spring.",
"A {} flower standing out.",
"A stunning image of {}.",
"A detailed drawing of {}.",
"The charming appearance of {}.",
"An image of {} in its natural habitat.",
"A {} flower in the morning light.",
"A {} plant with distinctive features.",
"A colorful field of {}.",
"A pastel painting of {}.",
"A photograph showcasing {}.",
"The intricate details of a {} flower.",
"A wild {} in its natural environment.",
"A charcoal sketch of {}.",
"A beautiful bouquet of {}.",
"The lovely sight of {} in bloom.",}
FOOD101_SELECTED = {
    "A photo of a delicious {}.",
"This is a picture of {}.",
"A {}, freshly cooked and ready to serve.",
"An image depicting a tasty {}.",
"This is a close-up shot of a {}.",
"A classic example of a {}.",
"This dish is a traditional {}.",
"A dish on a plate is a {}.",
"This is a photograph of a {}.",
"This is a {}, served in a restaurant.",
"A {}, prepared by a professional chef.",
"This is a {}, fresh from the kitchen.",
"This looks like a recipe for {}.",
"The dish in this photo is {}.",
"This dish, known as {}, originates from...",
"In this image, there is a {}.",
"This is a home-cooked {}.",
"A plate of {}, ready to eat.",
"An image clearly showing a {}.",
"This image perfectly depicts a {}.",
"This is a photograph of a popular dish, {}.",
"A delicious {}, cooked to perfection.",
"This is a picture of a dish commonly known as {}.",
"This looks like a {}, a popular dish.",
"This looks like a freshly made {}.",
"This is a serving of {}.",
"A tempting {}, presented beautifully.",
"This is a plate full of {}.",
"An appealing image of {}.",
"A well-presented {}.",
"This picture represents a {}.",
"This image features a {}.",
"The meal in this image is a {}.",
"A traditional serving of {}.",
"An appetizing {}.",
"A {}, typical in many cuisines.",
"This looks like a {}, a common dish.",
"The featured dish is a {}.",
"This image illustrates a {}.",
"This picture was taken while preparing {}.",
"A {}, just out of the oven.",
"This is a dish called {}.",
"This photo shows the preparation of a {}.",
"A tasty {}, straight from the stove.",
"This is a freshly baked {}.",
"The meal depicted here is a {}.",
"A classic {}, enjoyed worldwide.",
"This image represents a dish named {}.",
"This is an authentic {}.",
"A picture of a {}, garnished and served.",
"A {}, a culinary delight.",
"A {}, ready for the tasting.",
"This is a delectable {}.",
"This picture captures a {}.",
"A photograph of a {}, a beloved dish.",
"This looks like a homemade {}.",
"A {}, served hot and fresh.",
"A well-cooked {}, a feast for the eyes.",
"A {}, a treat for the palate.",
"A {}, garnished to perfection.",
"This image captures the essence of a {}.",
"A {}, a dish to savor.",
"A picture of a {}, a feast for the senses.",
"This is a delightful {}.",
"A picture of a classic {}.",
"An image of a traditional {}.",
"A photo of a {}, a gastronomic experience.",
"This is a beautifully presented {}.",
"An image of a typical {}.",
"This looks like a {}, a popular comfort food.",
"This image showcases a classic {}.",
"A photo of a {}, a culinary masterpiece.",
"This is a signature {}.",
"A photo capturing the flavors of a {}.",
"This image depicts a {}, a dish full of flavors.",
"A picture of a {}, a feast for the taste buds.",
"This is a serving of delicious {}.",
"A {}, a symbol of great cuisine.",
"An image that makes you crave for a {}.",
"This is a {}, a meal to remember.",
}
OXFORD_PETS_SELECTED = {
    "A photo of a {}.",
"This is a {}.",
"The animal in the picture is a {}.",
"A close-up view of a {}.",
"A high-resolution image of a {}.",
"A picture of a typical {}.",
"This image represents a {}.",
"This is a picture of a {}.",
"A picture of a mature {}.",
"The pet breed in the image is a {}.",
"The {} is the breed of this pet.",
"This is what a {} looks like.",
"A detailed photograph of a {}.",
"A {} is in the image.",
"A side profile view of a {}.",
"An image depicting a {}.",
"The domestic pet shown is a {}.",
"This photo is of a {}.",
"A {} breed cat/dog is shown in this image.",
"A photo showcasing a {}.",
"This is a pet breed called {}.",
"A photograph featuring a {}.",
"A beautiful example of a {}.",
"A typical representation of a {}.",
"This is an animal of the {} breed.",
"A {} captured in a photo.",
"The breed of the pet shown is {}.",
"A full body image of a {}.",
"The feline/canine breed in the picture is a {}.",
"An example of a {}.",
"A portrait of a {}.",
"This is how a {} looks like.",
"A clear image of a {}.",
"This animal belongs to the {} breed.",
"This photograph showcases a {}.",
"A professional shot of a {}.",
"The breed of this animal is {}.",
"A snapshot of a {}.",
"This picture features a {}.",
"A photo depicting a {}.",
"A {} is presented in the image.",
"This photograph displays a {}.",
"This {} is pictured.",
"A perfect representation of a {}.",
"The animal breed displayed is a {}.",
"This image showcases a breed called {}.",
"A profile shot of a {}.",
"The animal in this photo belongs to the {} breed.",
"An image showing the characteristics of a {}.",
"A distinct {} is in the picture.",
"This is an example of a {}.",
"The {} breed is shown in this photo.",
"This is an illustration of a {}.",
"This photograph was taken of a {}.",
"This image provides a good view of a {}.",
"An image depicting the physical characteristics of a {}.",
"A typical {} is pictured.",
"The pet breed known as {} is shown in this image.",
"The pet in the image is of the {} breed.",
"This is a characteristic {}.",
"An image showing a {}.",
"A clear picture of a {}.",
"The breed shown in the picture is a {}.",
"A characteristic representation of a {}.",
"This picture gives a good view of a {}.",
"A photograph of a well-groomed {}.",
"This photograph reveals a {}.",
"A {} is displayed in this photograph.",
"This is a representative {}.",
"The dog/cat breed called {} is shown in this photograph.",
"The {} breed is evident in this image.",
"The picture captures a {}.",
"A quality image of a {}.",
"An excellent depiction of a {}.",
"A {} is represented in this picture.",
"The animal featured in this image is a {}.",
"A headshot of a {}.",
"A splendid image of a {}.",
"The creature in this image is a {}.",
"The breed in focus is a {}.",
}
SUN397_SELECTED = {
"A photo of a {}.",
"An image showing a typical {}.",
"This is a picture of a {}.",
"An illustration of a {}.",
"A close-up view of a {}.",
"A {} in its natural environment.",
"An aerial view of a {}.",
"An artist's rendition of a {}.",
"A black and white photograph of a {}.",
"A vibrant, colorful {}.",
"A {} at night.",
"A {} during the day.",
"A panoramic view of a {}.",
"A classic example of a {}.",
"An iconic {}.",
"A modern representation of a {}.",
"A vintage picture of a {}.",
"A {} found in the wild.",
"A {} found in an urban setting.",
"A {} in a rural scene.",
"A scenic {}.",
"An abstract representation of a {}.",
"A detailed photograph of a {}.",
"A {} in its typical setting.",
"An unusual {}.",
"A beautiful {}.",
"A {} in action.",
"A {} taken from a unique angle.",
"A high-definition image of a {}.",
"An extreme close-up of a {}.",
"A {} in a historical context.",
"A {} with distinct features.",
"A silhouette of a {}.",
"A {} in a surreal context.",
"A {} in a minimalist setting.",
"A photographic representation of a {}.",
"A {} in a dramatic scene.",
"A {} captured at sunrise.",
"A {} photographed at sunset.",
"An antique {}.",
"A {} in an artistic composition.",
"A {} viewed from above.",
"A {} seen from below.",
"A {} captured during a special event.",
"A {} associated with a specific culture.",
"A {} commonly found in a specific geographical region.",
"A symbolic representation of a {}.",
"A {} framed by natural elements.",
"A {} embedded in a narrative context.",
"A {} as seen in popular media.",
"An animated {}.",
"A {} from a bird's-eye view.",
"A {} that is an important landmark.",
"A {} that signifies a particular time period.",
"A {} in a dream-like context.",
"A realistic depiction of a {}.",
"A {} in an unexpected location.",
"A {} in a high contrast scene.",
"A monochromatic {}.",
"A {} in a low light setting.",
"A {} captured in a long exposure shot.",
"A {} that shows signs of age and history.",
"A {} viewed through a fish-eye lens.",
"A {} that has a futuristic feel.",
"A {} with a play of light and shadows.",
"A {} photographed in infrared.",
"A {} as seen through thermal imaging.",
"A {} with a high saturation of colors.",
"A {} in sepia tones.",
"A {} with an emphasis on its texture.",
"A {} incorporated into a collage.",
"A {} digitally enhanced to highlight certain features.",
"A {} in a wide-angle shot.",
"A {} seen through a macro lens.",
"A {} that represents a certain style or movement in art.",
"A {} captured with a pinhole camera.",
"A {} depicted in a cubist style.",
"A {} represented in an impressionist manner.",
"A {} that is part of a sequence or series.",
"A {} reflected in water, glass, or another reflective surface.",
}
STANFORD_CARS_SELECTED = {
"A photo of a {}.",
"This is an image of a {}.",
"A close-up picture of a {}.",
"A beautiful {} in a parking lot.",
"A {} on the road.",
"A front view of a {}.",
"A rear view of a {}.",
"A {} in motion.",
"A {} under the sun.",
"A {} in the night.",
"A detailed image of a {}.",
"A black and white picture of a {}.",
"A {} with its headlights on.",
"The interior of a {}.",
"The engine of a {}.",
"A vintage {}.",
"A modern {}.",
"A custom-built {}.",
"A {} with an open trunk.",
"A {} from the side.",
"A {} with tinted windows.",
"A close-up of a {}'s wheel.",
"An artistic photo of a {}.",
"A red {}.",
"A blue {}.",
"A {} in a showroom.",
"The dashboard of a {}.",
"A {} with a custom paint job.",
"A fast {}.",
"A luxurious {}.",
"A sporty {}.",
"An off-road {}.",
"A {} with a spoiler.",
"A {} racing on a track.",
"A {} in a garage.",
"The backseat of a {}.",
"A {} with a convertible top.",
"A {} with a sunroof.",
"A {} with a racing stripe.",
"A {} with alloy wheels.",
"A silhouette of a {}.",
"A detailed sketch of a {}.",
"A {} in a cityscape.",
"A {} with a leather interior.",
"An eco-friendly {}.",
"The brake light of a {}.",
"A {} with fog lights.",
"A {} cruising on a highway.",
"A {} parked near the beach.",
"A {} reflecting the sunset.",
"A {} with a personalized license plate.",
"A {} at a car wash.",
"A green {}.",
"A white {}.",
"A {} with tinted tail lights.",
"The profile of a {}.",
"A {}'s exhaust pipe.",
"The rear mirror of a {}.",
"The door handle of a {}.",
"A {} with a matte finish.",
"A {} with glossy paint.",
"A {}'s logo.",
"A top-down view of a {}.",
"A {} with a roof rack.",
"A {} with a bike rack.",
"A {} with snow chains.",
"A {} with a trailer hitch.",
"A {}'s front grille.",
"A {} with neon underglow.",
"A {} on a country road.",
"A {} in a bustling city.",
"A {} on a mountain road.",
"A {} during winter.",
"A {} during summer.",
"A {} on a rainy day.",
"The gear shift of a {}.",
"A {}'s steering wheel.",
"A {} with tinted headlights.",
"A {} with customized decals.",
"A {}'s gas cap.",
}



INIT_TEMPLATES = {
    'coop': COOP_SELECTED,
    'openai': OPENAI_SELECTED,
    'laioncoco' : LAIONCOCO_SELECTED,
    'handcrafted': HANDCRAFTED_SELECTED,   
    'gpt-4': GPT4_SELECTED, 
    'eurosat': EUROSAT_SELECTED, 
    'ucf101': UCF101_SELECTED, 
    'imagenet': IMAGENET_SELECTED, 
    'caltech101': CALTECH101_SELECTED,
    'fgvc_aircraft': FGVC_AIRCRAFT_SELECTED,
    'dtd': DTD_SELECTED,
    'oxford_flowers': OXFORD_FLOWERS_SELECTED,
    'food101': FOOD101_SELECTED,
    'oxford_pets': OXFORD_PETS_SELECTED,
    'sun397': SUN397_SELECTED,
    'stanford_cars': STANFORD_CARS_SELECTED,
}
